### ISSUE TITLE
Why are the catalog files *still* blank?

### ISSUE THREAD

**Issue by DrTobogganMD** [BSData/wh40k-apocalypse#1]
Because the game's not out ya git!

**Comment by DrTobogganMD** [comment]
Because we're slow. They'll be out Soon^tm!

**Comment by Spoonete** [comment]
Hi! When can we download Apocalypse for battlescribe?

**Comment by TurbulentCaterwocky** [comment]
Just one last cat left! @GenWilhelm is going to deliver us some awesome :)

**Comment by GenWilhelm** [comment]
It's now available on appspot. Have at ye!
