### ISSUE TITLE
[Anon] Bug report: Imperium - Dark Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-apocalypse#122]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.12

**Platform:** Android

**Dropbox:** No

**Description:** Since the last update you can no longer select any relics on any characters in a Dark Angel detachment unless you use the Relics of the Rock stratagem, and if you select that stratagem you can only select 1 relic instead of the 2 you should be able to select.

**Comment by Mad-Spy** [comment]
There are no Relics in Apocalypse, I think you meant to open this in the main 40k repo.
