### ISSUE TITLE
[Anon] Bug report: Aeldari - Ynnari.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-apocalypse#128]
**File:** Aeldari - Ynnari.catz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** Yes

**Description:** With Yvraine or the Yncarne in a Craftworld detachment, the Craftworld Attribute can be selected as "Ynnari", but for a craftworld detachment with the Visarch in, "Ynnari" cannot be selected as the craftworld attribute. By the Ynnari rules from Psychic Awakening: Phoenix Rising, any of these 3 should allow the player to choose for the detachment to become Ynnari in replacement of the craftworld attributes, so the Visarch should also give this option.

**Comment by Mad-Spy** [comment]
These are 40k rules, not Apocalypse rules.
