### ISSUE TITLE
[Anon] Bug report: Aeldari - Ynnari.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-apocalypse#129]
**File:** Aeldari - Ynnari.catz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** Yes

**Description:** The fixed warlord traits for Yvraine and the Yncarne are outdated; they are the warlord traits from the White Dwarf Ynnari rules, which were changed in Psychic Awakening: Phoenix Rising (p76). Yvraine's should be changed from "Favoured of Ynnead" to "Warden of Souls", and the Yncarne's should be changed from "Warden of Souls" to "Fear of the Grave". The Visarch's trait appears to be correct. These have been seen on various occasions but can be seen by creating a supreme command detachment (Craftworld/Drukhari/Harlequin), adding the 3 Ynnari characters, setting them all as Warlord and seeing the available Warlord traits.

**Comment by Mad-Spy** [comment]
You appear to have raised this in the wrong repo. Phoenix Rising had rules for 40k proper, not Apocalypse.
