### ISSUE TITLE
Aeldari: Add Craftworlds/Masques

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-apocalypse#134]
**File:** Warhammer 40,000 Apocalypse.gstz

**BattleScribe version:** 2.03.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Anyway we can add the Craftworld and Masque designations to each selection for ease of playing? Most cards reference them and having in BS would be very nice! Thanks

**Comment by FarseerVeraenthis** [comment]
I did not know about this, I'll see what I can do 😄

**Comment by Mad-Spy** [comment]
@FarseerVeraenthis I haven't done anything with this because it seems pointless? It has no effect on list building. Players should be able to remember which subfaction they are playing as.

**Comment by Mad-Spy** [comment]
Closing as we're not going to do this.
