### ISSUE TITLE
[Anon] Bug report: Imperium - Blood Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-apocalypse#137]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** According to the Field Manual, Blood Talons are supposed to be 35 not 45. I was going to say something about the missing hand flamers, but you guys are no it already. Keep up the good work!

**Comment by Mad-Spy** [comment]
40k issue, not Apoc issue
