### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-apocalypse#140]
**File:** Orks.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Kustom Stompa standard weapons are incomplete. Gaze of Mork, MegaKlaw, Big Shootas are missing.

**Comment by Mad-Spy** [comment]
Duplicate of #138
