### ISSUE TITLE
Thousand Son datafile issues

### ISSUE THREAD

**Issue by efinest** [BSData/wh40k-apocalypse#142]
**File/Catalogue:** Thousand Sons

**BattleScribe version:** 2.01.

**Platform:** Linux

**Dropbox:** ?

**Description:**  

Ruberic Marine costs are wrong (4/7/?/?) instead of 5/9/13/17.  Also, the Soul Reaper upgrades should add +1 power each.

Scarab Occult Terminators should have Deep Strike. 

Forgefiends seem to have an extra Weapon line which affects printout

**Comment by Mad-Spy** [comment]
Issues 1 and 2 fixed. Unable to replicate 3rd problem. If you can provide details, I'll take another look.

**Comment by efinest** [comment]
Thanks... I can't seem to replicate the 3rd issue either post update, so I'm not going to worry about it.
