### ISSUE TITLE
Space Marine Issues

### ISSUE THREAD

**Issue by normanthesquid** [BSData/wh40k-apocalypse#144]
**File/Catalogue:** Space Marine Library and Adeptus Astartes Catalog

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The following issues exist for the Space Marine datasheets:
1. ~~Aggressors - missing Fragstorm Launchers~~ not missing.
2. ~~Aggressors - 3 model profile (A/W) is wrong~~ appears to be fine.
2. Primaris Chaplain is missing the Infantry category
3. Primaris Ancient is missing the Banner ability
4. Company Ancient is missing the Banner Ability
5. Chapter Ancient has the Banner, but it is hardcoded for Dark Angels instead of \<Chapter\>
6. Attack Bike Squad - 3 model wounds is wrong

**Comment by Technoblazed** [comment]
1) It's there under "Auto Boltstorm Gauntlets/Fragstorm Grenade Launchers.
2) Not really sure what this means? Aggressors have 3 attacks (4 for the sergeant) and 3 wounds each.
3) He has it.
4) He has it.
5) He has it.
6) That's incorrect, it states `<CHAPTER> CORE`.
7) They have 4 wounds in the data.
8) The weapon validation works fine.

Given that every single bug you just reported doesn't exist in the latest release, I would recommend that you update your data.

**Comment by Mad-Spy** [comment]
/release
A bunch of overdue fixes
