### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-apocalypse#149]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** For the Astra Militarum Infantry Squad, I'm getting an error for the Special Weapons trooper. If you select anything but the Sniper Rifle, you get an error

**Comment by Mad-Spy** [comment]
This sounds like a 40k proper issue, not Apocalypse. Please raise it in the correct data set.
