### ISSUE TITLE
[Anon] Bug report: Chaos - Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-apocalypse#151]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Biologus putrifier and other elite characters are missing

**Comment by Mad-Spy** [comment]
Pretty sure this should be in the main 40k repo, not Apoc.
