### ISSUE TITLE
Chaos - Heretic Astartes: Word Bearers are incorrectly forced to be Khorne

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-apocalypse#153]
**File:** Chaos - Heretic Astartes.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Word Bearers legion filter makes all units require mark of Khorne.

**Comment by Mad-Spy** [comment]
/release
Heretic Astartes fix

**Comment by Mad-Spy** [comment]
/release
Heretic Astartes fix

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/816271075)
Created release:
[v1.1.9](https://github.com/BSData/wh40k-apocalypse/releases/tag/v1.1.9)
**Heretic Astartes fix**
