### ISSUE TITLE
Krom Dragongaze gets a surprised emoji when you make him a commander

### ISSUE THREAD

**Issue by normanthesquid** [BSData/wh40k-apocalypse#157]
**File/Catalogue:** Imperium - Space Wolves v6

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** There is an extra "set Name to 0" modifier on Krom Dragongaze's commander option that makes it look kinda funny after you add him to a list.

![image](https://user-images.githubusercontent.com/858910/118863836-5f244e80-b8ad-11eb-9f31-8e2b104aff8b.png)

**Comment by Mad-Spy** [comment]
/release
More fixes

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/863345115)
Created release:
[v1.1.10](https://github.com/BSData/wh40k-apocalypse/releases/tag/v1.1.10)
**More fixes**
