### ISSUE TITLE
Big mek missing options when in mega armour

### ISSUE THREAD

**Issue by normanthesquid** [BSData/wh40k-apocalypse#158]
**File/Catalogue:** Orks v9

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The big mek is missing the following wargear options when equipped:

Can be equipped with a tellyport blasta (Power Rating +1) or can also have a Kustom Forcefield (Power Rating +1). If this unit has a Kustom Force Field it has the following additional abilities: Kustom Forcefield

Tellyport Blasta Profile:
Type: Heavy, Range: 12", Attacks: 1, SAP 9+, SAT 9+, Abilities: Destroyer

Kustom Force Field: Subtract 1 from wound rolls for attacks made by ranged weapons that target units whilst they are wholly within 9" of any friendly units with a Kustom Force Field

**Comment by Mad-Spy** [comment]
You just need to drill down in to the armour option after selecting it.
