### ISSUE TITLE
Ad Hoc Detachments not allowing additional forces within them

### ISSUE THREAD

**Issue by DreFace** [BSData/wh40k-apocalypse#160]
**File/Catalogue:** Warhammer 40,000 Apocalypse.gst

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Ad Hoc detachments are intended to allow inclusion of any number of units which do not fit in other detachments. However, it is impossible to add any additional unit sources to an Ad Hoc detachment, so it is e.g. impossible to put a unit from Adeptus Astartes and one from Astra Militarum in the same Ad Hoc detachment in BS despite this being intended in the core rules.

**Comment by Mad-Spy** [comment]
/release
June 2021 Release

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/955049892)
Created release:
[v1.1.11](https://github.com/BSData/wh40k-apocalypse/releases/tag/v1.1.11)
**June 2021 Release**
