### ISSUE TITLE
How to enter weapon abilities?

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-apocalypse#2]
We've seen from the Previews that weapons have abilities that are shared across multiple weapons (Inferno, Destroyer, etc.)

Will we be including rules for these weapons over and above including the Ability name in the weapon profile? If so, how should we implement them?

**Comment by amis92** [comment]
Sorry, I don't really understand what you propose.

I mean, I'd expect BattleScribe's output to match the one from wh community page:

![ork weapons table](https://www.warhammer-community.com/wp-content/uploads/2019/06/ApocFF_Orks-Jun19-KanWeaponz7gn.jpg)

So, we'd write the ability name in Abilities characteristic.

**Comment by GenWilhelm** [comment]
I agree with amis - match the source material in the actual profile.

We should probably have universal abilities as shared rules as well, so we can link them on a la 7e.

**Comment by DrTobogganMD** [comment]
Yep. Think 7th for weapon abilities. Links to shared rules so we match book profiles closely.

**Comment by Mad-Spy** [comment]
My point was that _should_ we copy the full weapon ability into the repo, if they do not have any text in the weapon profile over and above their name, as per @GenWilhelm's comment. To do so somewhat undermines the advertised "we are not a rulebook replacement" ethos.

The free datasheets do not have the weapon ability rules on them from what we can see so far. The only way to get those rules will be via the rulebook.

**Comment by DrTobogganMD** [comment]
Yes, we should.  If you want to get into that debate, we should take out everything not publicly available in the 40k repo proper :/

**Comment by amis92** [comment]
I agree. We quote rules and provide reference. It's enough. One can always hide them.
