### ISSUE TITLE
Warmaster Traits need a "Random" option

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k-apocalypse#21]
Warmaster Traits are, RaW, always random. You cannot select one. As these are generated after deployment, you shouldn't need to put them on the army list.

Now, I understand that this will probably be house ruled a lot, thus the need for them on the Battlescribe data, but a "00 - Randomly Determined" option would not go amiss.

**Comment by DrTobogganMD** [comment]
Bs does not support random choice. As coded I have it set to not require a trait. For exactly that reason. (I should have it set like that at least.  I'll double check tonight.)

**Comment by BaconCatBug** [comment]
True but if you select one you can't deselect it.

**Comment by DrTobogganMD** [comment]
Ahh yea that's not my intent. I'll edit that so there's a None option as in 40k
