### ISSUE TITLE
Supreme Command Detachment validation error

### ISSUE THREAD

**Issue by nottsknight** [BSData/wh40k-apocalypse#27]
Supreme Command Detachment raises an error after adding more than one unit: "{Force name} has {x} too many selections from Supreme Command Detachment (maximum 1)," where x is the number of units in the detachment -1.

Only tested with Thousand Sons, no idea if this is army specific.

**Comment by nalcon** [comment]
Confirming Issue on Supreme Command Detachment.

Core rules state 3-5 Minimum HQs. Error is thrown when more than 1 HQ is added.

Also, no error was thrown when there is more than 1 Supreme Command Detachment.

Core rules state only 1 Supreme Command Detachment is allowed per army.

**Comment by nalcon** [comment]
Addition: if a Supreme  Command Detachment is present, it must include the Warmaster in that detachment.

No error is thrown when Warmaster is not in Supreme Command Detachment, but is present in a different detachment.

**Comment by DrTobogganMD** [comment]
Restriction on Forces was enforcing on Selections. Fixed.
