### ISSUE TITLE
Supreme Command in Apoc

### ISSUE THREAD

**Issue by hatchetboy** [BSData/wh40k-apocalypse#31]
**File/Catalogue:** 

Apoc Astra Militarum and craft world eldar - presumably applies to all

**BattleScribe version:** 2.01.

iPhone 2.02.04

**Platform:** Windows/iOS/Android/Mac/Linux

iPhone 

**Dropbox:** Yes/No

Yes

**Description:** Detailed issue description.

Create a new roster. Add a supreme cmd detachment. Add 3 HQs. Validation error “roster has 3 too many selections of Supreme Command Detachment, max 0”

**Comment by GenWilhelm** [comment]
I followed those steps and didn't get the warning you describe. I got:

 - `1 too many forces from Supreme Command (max 0)` because it's a special detachment and there aren't any core detachments in the roster
- `Supreme Command Detachment must have 1 more selection of Warmaster (min 1)` because you must have your Warmaster in the Supreme Command if there is one in the roster.

Are there any other steps to reproducing the error?

**Comment by hatchetboy** [comment]
Don't think so.  On my phone:
1. + (new roster)
2. Select Apoc v4
3. Select Aeldari CW v6
4. Select Supreme Cmd Detatchement
5. Hit the tick
6. + on HQ
7. Select Autarch, Avatar of Kaine, Farseer
8. Hit the validation error (!) at the top
9. "New Roster (Warhammer 40,000: Apocalypse v4) has 3 too many selections from Supreme Command Detachment (maximum 0)" and "New Roster (Warhammer 40,000: Apocalypse v4) must have 1 more selections of Warmaster (minimum 1)"

You can get rid of the second one by selecting someone as warmaster, but you can't get rid of the first.

Interestingly I don't get the same error trying it on the desktop version of BS, something is screwy about the validation on mobile.

**Comment by GenWilhelm** [comment]
Aha, it's doing the same thing on android. Seems like it might be a bug in the mobile apps, rather than the data?

**Comment by hatchetboy** [comment]
I'm far from an expert, but I think there's an error in the GST, the constraint on the Supreme Cmd detatchment should be roster scope, nor selection?

`<constraint field="forces" scope="roster" value="0.0" percentValue="false" shared="true" includeChildSelections="false" includeChildForces="true" id="5c06-8d17-c698-baf4" type="max"/>`

I've done a quick test and that seems to fix the problem on mobile and the desktop version still works.

**Comment by GenWilhelm** [comment]
Oh, it's the child force causing issues. Yeah, that constraint shouldn't be there at all - good catch!
