### ISSUE TITLE
Eldar forgeworld missing

### ISSUE THREAD

**Issue by hatchetboy** [BSData/wh40k-apocalypse#32]
**File/Catalogue:** 

Craft worlds

**BattleScribe version:** 2.01.

2.02

**Platform:** Windows/iOS/Android/Mac/Linux

 iPhone

**Dropbox:** Yes/No

Yes

**Description:** Detailed issue description.

No FW in Super heavy slot, can’t see scorpion, cobra, FW wraith knight etc.  No Irrilyth in HQ.

**Comment by FarseerVeraenthis** [comment]
Big update just completed, units still outstanding are as follows;
- [x] Corsair Cloud Dancer Band
- [x] Corsair Reaver Band
- [x] Corsair Skyreaver Band
- [x] Corsair Venom
