### ISSUE TITLE
Strike team PL cost is 3 points too high

### ISSUE THREAD

**Issue by SmilingSilence** [BSData/wh40k-apocalypse#33]
**File/Catalogue:** T'au Empire

**BattleScribe version:** 2.02.03.299

**Platform:** Android

**Dropbox:** Yes

**Description:** Strike team costs 3 PL more than the actual cost of the unit.

Repro: 
1. Select strike team from troops section
2. Observe PL 6 (Expected PL 3 for 5 model unit)
3. Switch unit size to 10
4. Observe PL 9 (Expected PL 6)

I presume that there is a base cost of 3 PL added to the cost associated with the radio button selection of unit size + possible drones

**Comment by DrTobogganMD** [comment]
Fixed in https://github.com/BSData/wh40k-apocalypse/commit/3c501e3a93da0d579f0da15489542b6ad36c36aa
