### ISSUE TITLE
Vyper units are invalid when there are more than one model

### ISSUE THREAD

**Issue by SmilingSilence** [BSData/wh40k-apocalypse#34]
**File/Catalogue:** Craftworlds Aeldari

**BattleScribe version:** 2.02.03.299

**Platform:** Android

**Dropbox:** Yes

**Description:** Roster shows errors when you try to include a Vyper unit with more than one model. Errors seem to assume you would be able to select primary and secondary weapons separately for each model, but the selections are radio button lists.

Repro:
1. Add a Vyper unit to the roster
2. Select unit size 2 or 3 models
3. Observe error messages

Expected:
You should be able to select the loadout individually for each model as per the datasheet. This can be implemented as a list of counters for primary and secondary weapons as usual. Current validation should be fine.

**Comment by Mad-Spy** [comment]
@WindstormSCR, this is probably the BS bug where modifying constraints in a modifier group doesn't work.
