### ISSUE TITLE
Imperium - Imperial Knights: Unable to select multiple Knight Lances characters

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-apocalypse#39]
**File:** Imperium - Imperial Knights.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** when selecting multiple characters as given in the rulebook and character traits that are wip. just relax its not that. when setting up a detachment of super heavy and doing the selection of generating a character of the lance when having multiple shd .  in this current build you are restricted to have 1 character of  the lance when the rules state that you can have more then one .

**Comment by DrTobogganMD** [comment]
Fixed in 7491b57
