### ISSUE TITLE
Imperium - Adeptus Astartes: Multiple bugs

### ISSUE THREAD

**Issue by truec** [BSData/wh40k-apocalypse#42]
Astartes Aggressor Marines start at 8 PL for 3 models and should double to 16 PL for 6 models, instead the 6 model size is the same cost.

**Comment by DrTobogganMD** [comment]
I split your bug into two. the other is here #43

**Comment by DrTobogganMD** [comment]
Fixed in https://github.com/BSData/wh40k-apocalypse/commit/161fc336f24fe2213e2c02fb3d6661f84336007f
