### ISSUE TITLE
Detachments

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-apocalypse#5]
From the video on https://warhammer40000.com/apocalypse/

## Battalion Detachment
![1 battalion det](https://user-images.githubusercontent.com/2671396/60306180-8e3f1900-993f-11e9-8c9d-7a629be97cd5.png)

## Spearhead Detachment
![2 spearhead det](https://user-images.githubusercontent.com/2671396/60306182-91d2a000-993f-11e9-8c12-2539f416a951.png)

## Super-heavy Detachment
![3 super-heavy det](https://user-images.githubusercontent.com/2671396/60306183-939c6380-993f-11e9-84e3-882c01dab0e5.png)

## Air Wing Detachment
![4 air wing det](https://user-images.githubusercontent.com/2671396/60306185-94cd9080-993f-11e9-91ac-29bbf6ff06fb.png)

## Supreme Command Detachment
![5 command det](https://user-images.githubusercontent.com/2671396/60306188-96975400-993f-11e9-9453-b95e85330138.png)

## Vanguard Detachment
![6 vanguard det](https://user-images.githubusercontent.com/2671396/60306190-98f9ae00-993f-11e9-81e3-a41f5c0837c4.png)

**Comment by williamcaw** [comment]
All current detachments still apply. From the current Edition  including planet fall attack / defend, stronghold assault attack / defend ,Auxiliary support detachment, fortifications, super Heavy auxiliary detachment. From a preview game that I  attended yesterday.

**Comment by fuckingenglish** [comment]
Auxiliary detachments  can never gain faction ability's

**Comment by ghost** [comment]
Outrider Detachment is missing.

![Apocalypse 03 crop](https://user-images.githubusercontent.com/49225521/61098439-feb06480-a42c-11e9-8c41-e8d49563e47b.jpg)

**Comment by fuckingenglish** [comment]
for every one core detachment you can take one special detachment

**Comment by fuckingenglish** [comment]
fortification network detachment 1-3 min 1 " restriction this detachment may only be issued aimed fire orders "

**Comment by nalcon** [comment]
Reading from Special Detachments:

"You can include up to three Special Detachments in your army for every Core Detachment in your army."

Special Detachments are:

Patrol, Air Wing, Super-Heavy Auxiliary, Fortification, Supreme Command Detachment

Special note on Supreme Command Detachment:

Only one can be included in your army AND your warmaster must be a unit in this detachment.

**Comment by DrTobogganMD** [comment]
All logic and detachments have been implemented into GST.
