### ISSUE TITLE
Renegades and Heretics: Incorrect Covenant setup

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-apocalypse#52]
**File:** Warhammer 40,000 Apocalypse.gstz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Creating a Renegades and Heretics list. I’m prompted to select chaos covenant for all units, however only the warlord/commander of the detachment may choose and it applies  to all in the detachment (except plague ogryns). In the current set up each unit may pick any covenant and you theoretically have a mixed detachment.

**Comment by Mad-Spy** [comment]
This is incorrect. The R&H rules state that you choose the Covenant for each unit that has the `<CHAOS COVENANT>` keyword when you add it to your army.
![image](https://user-images.githubusercontent.com/29306451/62498687-f226ee00-b7d7-11e9-9435-c3dd98bd4cf6.png)
As far as this is concerned, you can have different Covenants in your army.

The Commander's rule adds additional bonuses for those units that share a keyword with the Commander.
