### ISSUE TITLE
Issue with commander counting and validating

### ISSUE THREAD

**Issue by Luctor-GH** [BSData/wh40k-apocalypse#55]
**File/Catalogue:** Dark Angels, Apocalypse

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** Number of commanders in a detachment is counted in an odd way sometimes, indicating that there are too many selections even when there are none checked in. Examples:
-Ezekiel and primaris liutenant in a vanguard detachment
-Primaris captain in a vanguard detachment
-Primaris liutenant ina  vanguard detachment
-Techmarine in a vanguard detachment

(seems similar to issue #43 , but in this case for Dark Angels)

**Comment by DrTobogganMD** [comment]
Thanks, didn't think to check the others in the SM library. Did this time, should be fixed for good *I hope*
