### ISSUE TITLE
Drukhari weapons

### ISSUE THREAD

**Issue by ithilnir** [BSData/wh40k-apocalypse#61]
File/Catalogue: Aeldari - Drukhari

BattleScribe version: 2.02.04

Platform: Windows/iOS

Dropbox: Yes

Description: Scourge weapon costs are wrong. Should be +2 for shredder and splinter cannon, +1 for blaster, dark lance, haywire, heat lance (currently no cost for blaster, haywire, heat lance).

Dark lance costs are also wrong on Razorwing Jetfighters, Ravagers, and Raiders; should be no cost (currently they are +1 PL).

Dark lances are an additional weapon on scourges which is why they are +1 PL; they replace a disintegrator on the vehicles so they are free on those.

**Comment by FarseerVeraenthis** [comment]
should be fixed with the next release, looks like I had the Dark Lance down as 1PL flat for everyone, which obviously causes trouble everywhere it is not 1PL (such as the vehicles...)
