### ISSUE TITLE
 5-model intercessors have the profile for 10-man squad

### ISSUE THREAD

**Issue by Luctor-GH** [BSData/wh40k-apocalypse#74]
File: Imperium - Dark Angels.catz

BattleScribe version: 2.02.04

Platform: Android

Dropbox: Yes

Description: 5-model intercessors have the profile for 10-man squad

**Comment by Mad-Spy** [comment]
This was a problem in the library, neither Intercessors or Infiltrators had a condition on the change to the 10 man profile.

**Comment by Luctor-GH** [comment]
Aggresors also have this issue, in case it wasn't solved with this fix.
