### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-apocalypse#78]
**File:** Orks.catz

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** Yes

**Description:** Deffkoptas require 2 or more selections from Primary Weapons if you select Unit Size 3. But the primary weapons is an options box (so either Rokkits or Big Shoota) and I cannot selecta  number.

**Comment by Mad-Spy** [comment]
Duplicate of #73. Will be in next release.
