### ISSUE TITLE
Renegades and Heretics errors

### ISSUE THREAD

**Issue by Pseudo-normie** [BSData/wh40k-apocalypse#88]
**BattleScribe version:** 2.01.

**Platform:**
Android

**Dropbox:** No

**Description:** The Renegades and Heretics faction has a couple errors. The leman russ battle tank doesn't have the option to equip a lascannon as its hull weapon. A chimera with a heavy bolter as both the turret weapon and the hull weapon is shown as not a legal loadout, i don't see on the datasheet saying it can't take both.

**Comment by Mad-Spy** [comment]
1. Not sure what's happened there! It's missing for everyone so I'll get it fixed.

2. ~~The Chimera options are correct. It comes with a heavy bolter and multi-laser. The second bullet point on the data sheet states you can swap the multi-laser for a heavy bolter.~~
Having now re-read your comment, I see you mean that it errors when you take 2 heavy bolters! It'll need fixing.

**Comment by Pseudo-normie** [comment]
Sorry for the poorly worded chimera part. Thanks for the response!
