### ISSUE TITLE
Adeptus Astartes Changes

### ISSUE THREAD

**Issue by normanthesquid** [BSData/wh40k-apocalypse#90]
**File/Catalogue:** Imperium - Adeptus Astartes

**BattleScribe version:** 2.03.03

**Platform:** Windows

**Dropbox:** Yes

**Description:** 10/25/2019 FAQ had changes for Adeptus Astartes and FW adeptus astartes that should be implemented

**Comment by normanthesquid** [comment]
I'm gonna tackle these changes, but i apparently cant assign this to myself

**Comment by Mad-Spy** [comment]
- Remove Bike from Korsarro Khan and update keywords
- Update Kayvaan Shrike
- Update Tigurius
- Add Incursors (Library)
- Add Tor Garadon
- Add Adrax Agatone
- Add Iron Father Feirros
- Add Invictor (Library)
- Add Impulsor (Library)
- Add Terminus Ultra

**Comment by Mad-Spy** [comment]
FW changes:

- Terrax assault drill Volkite charger profile
- Terrax PL cost
- Add Sicaran Arcus
- Add Sicaran Omega
- Relic Contemptor: change plasma blastgun to plasma blaster
- Add Gabriel Angelos
- Add Carab Culln the Risen
